name: StrawberryOS Base Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt install -y debootstrap podman wget git

    - name: Install simu
      run: |
        sudo mkdir /workdir
        sudo wget https://github.com/Strawberry-Foundations/simu/raw/main/simu -O /workdir/simu
        sudo chmod a+x /workdir/simu

    - name: Build rootfs
      run: |
        cd /workdir
        sudo wget https://raw.githubusercontent.com/Strawberry-Foundations/os-images/main/base.yml
        sudo ./simu base.yml
        cd /workdir
        sudo mv /rootfs.tar /workdir/rootfs.tar

    - name: Build the Docker image
      run: cd && docker image build -f /workdir/Dockerfile --tag ghcr.io/strawberry-foundations/os-base:latest .

    - name: Create SHA256SUMS
      run: |
        sha256sum rootfs.tar > SHA256SUMS
        cd ..

    # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      run: |
         docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
         docker image push "ghcr.io/strawberry-foundations/os-base:latest"

    - uses: actions/upload-artifact@v4
      with:
        name: rootfs
        path: cd /workdir/rootfs.tar